[[override]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[override]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[override]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.13.4"