apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3s.ssc.aws.abc.com
spec:
  group: aws.ssc.aws.abc.com
  version: v1alpha1
  names:
    kind: S3
    plural: s3s
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 1
